export const templateDelegateHpp = `/********************************************************************************
** This file is auto generated by vscode-qtdao.
** Don't modify this file!
********************************************************************************/
#pragma once

#include <qobject.h>

namespace Dao$SqlType$ {
    class $SqlType$EntityDelegate : public QObject {
        Q_OBJECT

    public:
        Q_INVOKABLE explicit $SqlType$EntityDelegate() = default;

        Q_INVOKABLE void createEntityTables();

        Q_INVOKABLE void entityTablesUpgrade(int oldVer, int newVer);
    };
}
Q_DECLARE_METATYPE(Dao$SqlType$::$SqlType$EntityDelegate*);`;